# vim:ft=kitty
## name: HyprV Dark
## source: Konsole One-Dark / HyprV ghostty dark + Catppuccin accents
## paired with: theme.conf

foreground              #fcfcfc
background              #1e222a
selection_foreground    #1e222a
selection_background    #89b4fa

cursor                  #fcfcfc
cursor_text_color       #1e222a
cursor_trail_color      #89b4fa

url_color               #89b4fa

active_border_color     #89b4fa
inactive_border_color   #45475a
bell_border_color       #71839d
visual_bell_color       #303a4b

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #11111b
active_tab_background   #89b4fa
inactive_tab_foreground #cdd6f4
inactive_tab_background #272b32
tab_bar_background      #1e222a
tab_bar_margin_color    #1e222a

mark1_foreground #1e222a
mark1_background #89b4fa
mark2_foreground #1e222a
mark2_background #f5c2e7
mark3_foreground #1e222a
mark3_background #94e2d5

# black
color0  #272b32
color8  #585b70

# red
color1  #f38ba8
color9  #f38ba8

# green
color2  #a6e3a1
color10 #a6e3a1

# yellow
color3  #f9e2af
color11 #f9e2af

# blue
color4  #89b4fa
color12 #89b4fa

# magenta
color5  #f5c2e7
color13 #f5c2e7

# cyan
color6  #94e2d5
color14 #94e2d5

# white
color7  #bac2de
color15 #a6adc8
