#!/bin/bash

get_theme() {
    THEMEIS=$(~/.config/HyprV/quickshell/scripts/ui-state.sh get-theme)

    if [[ $THEMEIS == "dark" ]]; then
        SWITCHTO="-dark"
        MODESTR="Dark"
    else
        SWITCHTO=""
        MODESTR="Light"
    fi
}

get_ver() {
    VER=$(~/.config/HyprV/quickshell/scripts/ui-state.sh get-variant)
}

set_current_background() {
    get_theme
    get_ver
    
    #set the current background
    if [[ $THEMEIS == "dark" ]]; then
        swww img ~/.config/HyprV/backgrounds/$VER'-background-dark.jpg' --transition-fps 60 --transition-type wipe --transition-duration 4
    else
        swww img ~/.config/HyprV/backgrounds/$VER'-background.jpg' --transition-fps 60 --transition-type wipe --transition-duration 4
    fi
}

switch_version() {
    get_theme
    get_ver
    case $VER in
        v1)
            VERTO="v2"
        ;;
        
        v2)
            VERTO="v3"
        ;;

        v3)
            VERTO="v1"
        ;;
        bt)
            VERTO="v3"
        ;;
    esac
    ~/.config/HyprV/quickshell/scripts/set-variant.sh "$VERTO"

}

if [[ "$1" == "vswitch" ]]; then
    switch_version
elif [[ "$1" == "setbg" ]]; then
    set_current_background
fi

# need to show the version and tooltip
get_ver

TOOLTIP='Default Keybinds\n'\
'SUPER + Q = Start Kitty\n'\
'SUPER + F4 = Close Window\n'\
'SUPER + L = Lock Screen\n'\
'SUPER + M = Logout menu\n'\
'SUPER + E = File Manager\n'\
'SUPER + V = Toggle Float\n'\
'SUPER + SPACE = App Launcher\n'\
'SUPER + S = Screenshot'

echo '{"text": "'$VER'", "tooltip": "'$TOOLTIP'"}'
