# tty drop down
#$dropterm = alacritty-dropdown
windowrule {
  name = dropdown-terminal
  match:class = ^(alacritty-dropdown)$
  size = 1080 225
  float = on
  #pin = on
  move = monitor_w*0.125 60  # note the ending %
}
bind = $mainMod SHIFT,T,exec,$HOME/.config/hypr/scripts/dropdown.sh

# chat drop down
bind = $mainMod, SPACE, exec, bash $HOME/.config/hypr/scripts/sidechat.sh
bind = SUPER SHIFT, F23, exec, bash $HOME/.config/hypr/scripts/sidechat.sh
windowrule {
  name = dropdown-ai-hub
  match:class = ^(ai-hub|electron)$
  match:title = ^(AI Hub)$
  float = on
  animation = slide
  size = 360 monitor_h-72
  move = monitor_w-370 60
  #pin = on
}

windowrule {
  name = pin-meeting
  match:class = (Meeting)$
  pin = on
}

# Calendar dropdown
bind = $mainMod,C, exec, ~/.config/HyprV/hypr/scripts/dropcalender.sh
windowrule {
  name = dropdown-calendar
  match:class = ^(chrome-calendar\.google\.com.*Default)$
  float = on
  size = monitor_w*0.592 monitor_h*0.6
  move = monitor_w*0.4 60
}
